"""CLI helpers for Raw certification Databricks Python script tasks."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

from napa_pipeline.certification.config import (
    ALLOWED_RELEASE_ALIASES,
    normalize_release_name,
)


class CertificationCliError(RuntimeError):
    """Raised when a script task cannot access required Databricks globals."""


def add_release_argument(parser: argparse.ArgumentParser) -> None:
    """Add the shared certification release argument to a script parser."""
    parser.add_argument(
        "--release-type",
        required=True,
        type=normalize_release_name,
        help=(
            "Release to certify. Accepted aliases: "
            + ", ".join(ALLOWED_RELEASE_ALIASES)
            + "."
        ),
    )


def add_config_path_argument(parser: argparse.ArgumentParser) -> None:
    """Add the optional shared config path argument to a script parser."""
    parser.add_argument(
        "--config-path",
        default=None,
        help="Optional path to config/certification. Defaults to the repo config.",
    )


def add_analysis_as_of_date_argument(parser: argparse.ArgumentParser) -> None:
    """Add the optional analysis-as-of-date argument to a script parser."""
    parser.add_argument(
        "--analysis-as-of-date",
        default="",
        help="Optional analysis date override in YYYY-MM-DD format.",
    )


def add_source_snapshot_path_argument(parser: argparse.ArgumentParser) -> None:
    """Add the optional source-snapshot path argument to a script parser."""
    parser.add_argument(
        "--source-snapshot-path",
        default="",
        help="Optional JSON snapshot path for source/export reconciliation.",
    )


def add_baseline_id_argument(parser: argparse.ArgumentParser) -> None:
    """Add the optional baseline identifier argument to a script parser."""
    parser.add_argument(
        "--baseline-id",
        default="",
        help="Optional baseline identifier or snapshot reference for regression comparison.",
    )


def add_fail_on_argument(parser: argparse.ArgumentParser) -> None:
    """Add the release-gate fail-on severity argument to a script parser."""
    parser.add_argument(
        "--fail-on",
        default="blocker",
        help="Minimum severity that fails the workflow: blocker, error, warning, never.",
    )


def add_run_id_argument(parser: argparse.ArgumentParser, *, required: bool = True) -> None:
    """Add the shared certification run-id argument to a script parser."""
    parser.add_argument(
        "--run-id",
        required=required,
        help="Certification run identifier generated by resolve_configuration.",
    )


def normalize_config_path(config_path: str | None) -> Path | None:
    """Return a Path for a non-empty config path."""
    if config_path is None:
        return None
    stripped = config_path.strip()
    return Path(stripped) if stripped else None


def normalize_optional_string(value: str | None) -> str | None:
    """Return a stripped optional string, or None when blank."""
    if value is None:
        return None
    stripped = value.strip()
    return stripped or None


def get_databricks_global(name: str) -> Any:
    """Return a Databricks-provided global or fail with an actionable message."""
    main_module = sys.modules.get("__main__")
    value = getattr(main_module, name, None) if main_module is not None else None
    if value is not None:
        return value

    import builtins

    value = getattr(builtins, name, None)
    if value is not None:
        return value

    raise CertificationCliError(
        f"Databricks global '{name}' is not available. "
        "Run this file as a Databricks Python script task."
    )


def set_task_value(dbutils: Any, key: str, value: Any) -> None:
    """Set a Databricks task value when running inside a workflow."""
    try:
        dbutils.jobs.taskValues.set(key=key, value=value)
    except Exception:
        pass
