"""CLI helpers for Raw-to-Bronze Databricks Python script tasks."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any


RELEASE_TYPE_TO_RELEASE_NAME = {
    "5k": "napa_5k",
    "50k": "napa_50k",
    "250k": "napa_250k",
}
ALLOWED_RELEASE_TYPES = tuple(RELEASE_TYPE_TO_RELEASE_NAME.keys())


class RawToBronzeCliError(RuntimeError):
    """Raised when a script task cannot access required Databricks globals."""


def add_release_type_argument(parser: argparse.ArgumentParser) -> None:
    """Add the shared release-type argument to a script parser."""
    parser.add_argument(
        "--release-type",
        required=True,
        choices=ALLOWED_RELEASE_TYPES,
        help="Release scale to process. Allowed values: 5k, 50k, 250k.",
    )


def add_config_path_argument(parser: argparse.ArgumentParser) -> None:
    """Add the optional shared config path argument to a script parser."""
    parser.add_argument(
        "--config-path",
        default=None,
        help="Optional path to config/raw_to_bronze. Defaults to the repo config.",
    )


def add_run_id_argument(parser: argparse.ArgumentParser, *, required: bool = True) -> None:
    """Add the shared pipeline run-id argument to a script parser."""
    parser.add_argument(
        "--run-id",
        required=required,
        help="Pipeline run identifier generated by resolve_configuration.",
    )


def release_type_to_release_name(release_type: str) -> str:
    """Translate a workflow release_type into the existing release_name."""
    normalized = release_type.strip().lower()
    try:
        return RELEASE_TYPE_TO_RELEASE_NAME[normalized]
    except KeyError as exc:
        allowed = ", ".join(ALLOWED_RELEASE_TYPES)
        raise argparse.ArgumentTypeError(
            f"Unsupported release_type '{release_type}'. Allowed values: {allowed}."
        ) from exc


def normalize_config_path(config_path: str | None) -> Path | None:
    """Return a Path for a non-empty config path."""
    if config_path is None:
        return None
    stripped = config_path.strip()
    return Path(stripped) if stripped else None


def get_databricks_global(name: str) -> Any:
    """Return a Databricks-provided global or fail with an actionable message."""
    main_module = sys.modules.get("__main__")
    value = getattr(main_module, name, None) if main_module is not None else None
    if value is not None:
        return value

    import builtins

    value = getattr(builtins, name, None)
    if value is not None:
        return value

    raise RawToBronzeCliError(
        f"Databricks global '{name}' is not available. "
        "Run this file as a Databricks Python script task."
    )


def set_task_value(dbutils: Any, key: str, value: Any) -> None:
    """Set a Databricks task value when running inside a workflow."""
    try:
        dbutils.jobs.taskValues.set(key=key, value=value)
    except Exception:
        pass
