"""CLI helpers for Bronze-to-Silver Databricks Python script tasks."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

from napa_pipeline.bronze_to_silver.config import ALLOWED_RELEASES


class BronzeToSilverCliError(RuntimeError):
    """Raised when a script task cannot access required Databricks globals."""


def add_release_name_argument(parser: argparse.ArgumentParser) -> None:
    """Add the shared release-name argument to a script parser."""
    parser.add_argument(
        "--release-name",
        required=True,
        choices=ALLOWED_RELEASES,
        help="Release name to process. Allowed values: napa_5k, napa_50k, napa_250k.",
    )


def add_config_path_argument(parser: argparse.ArgumentParser) -> None:
    """Add the optional shared config path argument to a script parser."""
    parser.add_argument(
        "--config-path",
        default=None,
        help="Optional path to config/bronze_to_silver. Defaults to the repo config.",
    )


def add_run_id_argument(parser: argparse.ArgumentParser, *, required: bool = True) -> None:
    """Add the shared pipeline run-id argument to a script parser."""
    parser.add_argument(
        "--run-id",
        required=required,
        help="Pipeline run identifier generated by resolve_configuration.",
    )


def normalize_config_path(config_path: str | None) -> Path | None:
    """Return a Path for a non-empty config path."""
    if config_path is None:
        return None
    stripped = config_path.strip()
    return Path(stripped) if stripped else None


def get_databricks_global(name: str) -> Any:
    """Return a Databricks-provided global or fail with an actionable message."""
    main_module = sys.modules.get("__main__")
    value = getattr(main_module, name, None) if main_module is not None else None
    if value is not None:
        return value

    import builtins

    value = getattr(builtins, name, None)
    if value is not None:
        return value

    raise BronzeToSilverCliError(
        f"Databricks global '{name}' is not available. "
        "Run this file as a Databricks Python script task."
    )


def set_task_value(dbutils: Any, key: str, value: Any) -> None:
    """Set a Databricks task value when running inside a workflow."""
    try:
        dbutils.jobs.taskValues.set(key=key, value=value)
    except Exception:
        pass
