domains:
  country_code:
    allowed: [USA, CAN]
    synonyms:
      US: USA
      UNITED STATES: USA
      UNITED STATES OF AMERICA: USA
      CA: CAN
      CANADA: CAN

  gender:
    allowed: [M, F]
    synonyms:
      MALE: M
      FEMALE: F

  dominant_hand:
    allowed: [LEFT, RIGHT, AMBIDEXTROUS]
    synonyms:
      L: LEFT
      R: RIGHT
      BOTH: AMBIDEXTROUS

  player_status:
    allowed: [ACTIVE, INACTIVE]

  team_status:
    allowed: [ACTIVE, INACTIVE, DISSOLVED]
    synonyms:
      DORMANT: INACTIVE
      RETIRED: DISSOLVED

  team_type:
    allowed: [MENS, WOMENS, MIXED, OPEN]
    synonyms:
      MENS_DOUBLES: MENS
      WOMENS_DOUBLES: WOMENS
      MIXED_DOUBLES: MIXED
      OPEN_DOUBLES: OPEN

  player_position:
    allowed: [LEFT, RIGHT]
